import { useState, type FC } from "react";
import { Copy, Check, Download, Printer, MapPin, Plane, Calendar, DollarSign, Sparkles } from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import type { TripPlanResponse } from "../types";

interface ItineraryViewerProps {
  plan: TripPlanResponse;
}

export const ItineraryViewer: FC<ItineraryViewerProps> = ({ plan }) => {
  const [copied, setCopied] = useState(false);
  const content = plan.final_response || plan.final_answer || plan.itinerary || plan.answer || "";
  const constraints = plan.trip_constraints || {};

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // ignore
    }
  };

  const handleDownload = () => {
    const filename = `trip_itinerary_${(plan.destination || constraints.destination || "travel").replace(/\s+/g, "_").toLowerCase()}.md`;
    const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="w-full glass-panel rounded-2xl border border-slate-800 shadow-2xl overflow-hidden animate-fade-in">
      {/* Top Banner with Destination Details */}
      <div className="p-5 sm:p-6 bg-gradient-to-r from-indigo-950/70 via-purple-950/40 to-slate-900 border-b border-slate-800">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1.5">
              <span className="px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                ✨ Final Master Guide
              </span>
              <span className="text-xs text-slate-400 font-mono">
                Thread ID: {plan.thread_id}
              </span>
            </div>
            <h2 className="text-xl sm:text-2xl font-bold text-white flex items-center gap-2">
              <MapPin className="h-6 w-6 text-rose-400 shrink-0" />
              {plan.destination || constraints.destination || "Custom Vacation"}
            </h2>
            <p className="text-xs text-slate-300 mt-1 max-w-2xl">
              Generated by multi-agent collaboration with real-time airport routing, live hotel intelligence, and weather adaptation.
            </p>
          </div>

          {/* Quick Action Buttons */}
          <div className="flex items-center gap-2 self-start md:self-auto">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-slate-900/90 hover:bg-slate-800 border border-slate-700 text-xs font-semibold text-slate-200 transition-all active:scale-95"
              title="Copy itinerary to clipboard"
            >
              {copied ? (
                <>
                  <Check className="h-4 w-4 text-emerald-400" />
                  <span className="text-emerald-300">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="h-4 w-4 text-slate-400" />
                  <span>Copy</span>
                </>
              )}
            </button>

            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-slate-900/90 hover:bg-slate-800 border border-slate-700 text-xs font-semibold text-slate-200 transition-all active:scale-95"
              title="Download as Markdown file"
            >
              <Download className="h-4 w-4 text-indigo-400" />
              <span className="hidden sm:inline">Export .md</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-slate-900/90 hover:bg-slate-800 border border-slate-700 text-xs font-semibold text-slate-200 transition-all active:scale-95"
              title="Print itinerary"
            >
              <Printer className="h-4 w-4 text-purple-400" />
              <span className="hidden sm:inline">Print</span>
            </button>
          </div>
        </div>

        {/* Metadata Badges */}
        <div className="flex flex-wrap items-center gap-2.5 mt-4 pt-4 border-t border-slate-800/80 text-xs text-slate-300 font-medium">
          <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-slate-900/80 border border-slate-800">
            <Plane className="h-3.5 w-3.5 text-sky-400" />
            <span>Origin: <strong>{constraints.origin || "DAC"}</strong></span>
          </div>
          <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-slate-900/80 border border-slate-800">
            <Calendar className="h-3.5 w-3.5 text-indigo-400" />
            <span>Duration: <strong>{constraints.duration || "Flexible"}</strong></span>
          </div>
          <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-slate-900/80 border border-slate-800">
            <DollarSign className="h-3.5 w-3.5 text-emerald-400" />
            <span>Budget: <strong className="capitalize">{constraints.budget || "Standard"}</strong></span>
          </div>
          <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-slate-900/80 border border-slate-800">
            <Sparkles className="h-3.5 w-3.5 text-purple-400" />
            <span>Style: <strong className="capitalize">{constraints.travel_style || "General"}</strong></span>
          </div>
          {plan.llm_calls !== undefined && (
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-slate-900/80 border border-slate-800 text-slate-400 font-mono text-[11px] ml-auto">
              <span>LLM Calls: {plan.llm_calls}</span>
            </div>
          )}
        </div>
      </div>

      {/* Main Formatted Markdown Content */}
      <div className="p-6 sm:p-8 bg-slate-950/90 markdown-content">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {content}
        </ReactMarkdown>
      </div>
    </div>
  );
};
